//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Khachhang_View
    {
        public int maKh { get; set; }
        public string ho { get; set; }
        public string tenlot { get; set; }
        public string tenKh { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public string loaiKh { get; set; }
    }
}
