//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Khachhang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Khachhang()
        {
            this.Thues = new HashSet<Thue>();
        }
    
        public int maKh { get; set; }
        public string ho { get; set; }
        public string tenlot { get; set; }
        public string tenKh { get; set; }
        public string sdt { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public string loaiKh { get; set; }
        public int nguoiCapnhat { get; set; }
    
        public virtual Nhanvien Nhanvien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Thue> Thues { get; set; }
    }
}
