//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CKDBMSEntities : DbContext
    {
        public CKDBMSEntities()
            : base("name=CKDBMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Khachhang> Khachhangs { get; set; }
        public virtual DbSet<Nhanvien> Nhanviens { get; set; }
        public virtual DbSet<Phong> Phongs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Taikhoan> Taikhoans { get; set; }
        public virtual DbSet<Thue> Thues { get; set; }
        public virtual DbSet<Khachhang_View> Khachhang_View { get; set; }
        public virtual DbSet<Taikhoan_view> Taikhoan_view { get; set; }
        public virtual DbSet<ThueAd_view> ThueAd_view { get; set; }
        public virtual DbSet<ThueTN_view> ThueTN_view { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual ObjectResult<sp_chonKh_Result> sp_chonKh(Nullable<int> makh)
        {
            var makhParameter = makh.HasValue ?
                new ObjectParameter("makh", makh) :
                new ObjectParameter("makh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_chonKh_Result>("sp_chonKh", makhParameter);
        }
    
        public virtual ObjectResult<sp_chonnv_Result> sp_chonnv(Nullable<int> manv)
        {
            var manvParameter = manv.HasValue ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_chonnv_Result>("sp_chonnv", manvParameter);
        }
    
        public virtual ObjectResult<sp_chonphong_Result> sp_chonphong(string maphong)
        {
            var maphongParameter = maphong != null ?
                new ObjectParameter("maphong", maphong) :
                new ObjectParameter("maphong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_chonphong_Result>("sp_chonphong", maphongParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_datphong(string maphong, Nullable<int> makh, Nullable<int> mancc)
        {
            var maphongParameter = maphong != null ?
                new ObjectParameter("maphong", maphong) :
                new ObjectParameter("maphong", typeof(string));
    
            var makhParameter = makh.HasValue ?
                new ObjectParameter("makh", makh) :
                new ObjectParameter("makh", typeof(int));
    
            var manccParameter = mancc.HasValue ?
                new ObjectParameter("mancc", mancc) :
                new ObjectParameter("mancc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_datphong", maphongParameter, makhParameter, manccParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_loadDSKH_Result> sp_loadDSKH(string tukhoa, string loaitk)
        {
            var tukhoaParameter = tukhoa != null ?
                new ObjectParameter("tukhoa", tukhoa) :
                new ObjectParameter("tukhoa", typeof(string));
    
            var loaitkParameter = loaitk != null ?
                new ObjectParameter("loaitk", loaitk) :
                new ObjectParameter("loaitk", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_loadDSKH_Result>("sp_loadDSKH", tukhoaParameter, loaitkParameter);
        }
    
        public virtual ObjectResult<sp_loadDSP_Result> sp_loadDSP(string tinhtrang)
        {
            var tinhtrangParameter = tinhtrang != null ?
                new ObjectParameter("tinhtrang", tinhtrang) :
                new ObjectParameter("tinhtrang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_loadDSP_Result>("sp_loadDSP", tinhtrangParameter);
        }
    
        public virtual ObjectResult<sp_loadDSTP_Result> sp_loadDSTP(string tukhoa, string loaitk, string trangthai)
        {
            var tukhoaParameter = tukhoa != null ?
                new ObjectParameter("tukhoa", tukhoa) :
                new ObjectParameter("tukhoa", typeof(string));
    
            var loaitkParameter = loaitk != null ?
                new ObjectParameter("loaitk", loaitk) :
                new ObjectParameter("loaitk", typeof(string));
    
            var trangthaiParameter = trangthai != null ?
                new ObjectParameter("trangthai", trangthai) :
                new ObjectParameter("trangthai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_loadDSTP_Result>("sp_loadDSTP", tukhoaParameter, loaitkParameter, trangthaiParameter);
        }
    
        public virtual ObjectResult<sp_loadnv_Result> sp_loadnv(string tukhoa)
        {
            var tukhoaParameter = tukhoa != null ?
                new ObjectParameter("tukhoa", tukhoa) :
                new ObjectParameter("tukhoa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_loadnv_Result>("sp_loadnv", tukhoaParameter);
        }
    
        public virtual ObjectResult<string> sp_loainv()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_loainv");
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual ObjectResult<string> sp_selectLoaikh()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_selectLoaikh");
        }
    
        public virtual int sp_suakh(Nullable<int> makh, string ho, string tenlot, string tenkh, string sdt, Nullable<System.DateTime> ngaysinh, string loaiKh, Nullable<int> mancn)
        {
            var makhParameter = makh.HasValue ?
                new ObjectParameter("makh", makh) :
                new ObjectParameter("makh", typeof(int));
    
            var hoParameter = ho != null ?
                new ObjectParameter("ho", ho) :
                new ObjectParameter("ho", typeof(string));
    
            var tenlotParameter = tenlot != null ?
                new ObjectParameter("tenlot", tenlot) :
                new ObjectParameter("tenlot", typeof(string));
    
            var tenkhParameter = tenkh != null ?
                new ObjectParameter("tenkh", tenkh) :
                new ObjectParameter("tenkh", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var ngaysinhParameter = ngaysinh.HasValue ?
                new ObjectParameter("ngaysinh", ngaysinh) :
                new ObjectParameter("ngaysinh", typeof(System.DateTime));
    
            var loaiKhParameter = loaiKh != null ?
                new ObjectParameter("loaiKh", loaiKh) :
                new ObjectParameter("loaiKh", typeof(string));
    
            var mancnParameter = mancn.HasValue ?
                new ObjectParameter("mancn", mancn) :
                new ObjectParameter("mancn", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_suakh", makhParameter, hoParameter, tenlotParameter, tenkhParameter, sdtParameter, ngaysinhParameter, loaiKhParameter, mancnParameter);
        }
    
        public virtual int sp_suanv(Nullable<int> manv, string ho, string tenlot, string ten, Nullable<System.DateTime> ngaysinh, string sdt, string chucvu)
        {
            var manvParameter = manv.HasValue ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(int));
    
            var hoParameter = ho != null ?
                new ObjectParameter("ho", ho) :
                new ObjectParameter("ho", typeof(string));
    
            var tenlotParameter = tenlot != null ?
                new ObjectParameter("tenlot", tenlot) :
                new ObjectParameter("tenlot", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            var ngaysinhParameter = ngaysinh.HasValue ?
                new ObjectParameter("ngaysinh", ngaysinh) :
                new ObjectParameter("ngaysinh", typeof(System.DateTime));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var chucvuParameter = chucvu != null ?
                new ObjectParameter("chucvu", chucvu) :
                new ObjectParameter("chucvu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_suanv", manvParameter, hoParameter, tenlotParameter, tenParameter, ngaysinhParameter, sdtParameter, chucvuParameter);
        }
    
        public virtual int sp_suaphong(string maphong, string loaiphong, string capdo, Nullable<decimal> giaphong, string tinhtrang)
        {
            var maphongParameter = maphong != null ?
                new ObjectParameter("maphong", maphong) :
                new ObjectParameter("maphong", typeof(string));
    
            var loaiphongParameter = loaiphong != null ?
                new ObjectParameter("loaiphong", loaiphong) :
                new ObjectParameter("loaiphong", typeof(string));
    
            var capdoParameter = capdo != null ?
                new ObjectParameter("capdo", capdo) :
                new ObjectParameter("capdo", typeof(string));
    
            var giaphongParameter = giaphong.HasValue ?
                new ObjectParameter("giaphong", giaphong) :
                new ObjectParameter("giaphong", typeof(decimal));
    
            var tinhtrangParameter = tinhtrang != null ?
                new ObjectParameter("tinhtrang", tinhtrang) :
                new ObjectParameter("tinhtrang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_suaphong", maphongParameter, loaiphongParameter, capdoParameter, giaphongParameter, tinhtrangParameter);
        }
    
        public virtual int sp_themkh(string ho, string tenlot, string tenkh, string sdt, Nullable<System.DateTime> ngaysinh, Nullable<int> mancn)
        {
            var hoParameter = ho != null ?
                new ObjectParameter("ho", ho) :
                new ObjectParameter("ho", typeof(string));
    
            var tenlotParameter = tenlot != null ?
                new ObjectParameter("tenlot", tenlot) :
                new ObjectParameter("tenlot", typeof(string));
    
            var tenkhParameter = tenkh != null ?
                new ObjectParameter("tenkh", tenkh) :
                new ObjectParameter("tenkh", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var ngaysinhParameter = ngaysinh.HasValue ?
                new ObjectParameter("ngaysinh", ngaysinh) :
                new ObjectParameter("ngaysinh", typeof(System.DateTime));
    
            var mancnParameter = mancn.HasValue ?
                new ObjectParameter("mancn", mancn) :
                new ObjectParameter("mancn", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_themkh", hoParameter, tenlotParameter, tenkhParameter, sdtParameter, ngaysinhParameter, mancnParameter);
        }
    
        public virtual int sp_themnv(string ho, string tenlot, string ten, Nullable<System.DateTime> ngaysinh, string sdt, string chucvu)
        {
            var hoParameter = ho != null ?
                new ObjectParameter("ho", ho) :
                new ObjectParameter("ho", typeof(string));
    
            var tenlotParameter = tenlot != null ?
                new ObjectParameter("tenlot", tenlot) :
                new ObjectParameter("tenlot", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            var ngaysinhParameter = ngaysinh.HasValue ?
                new ObjectParameter("ngaysinh", ngaysinh) :
                new ObjectParameter("ngaysinh", typeof(System.DateTime));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var chucvuParameter = chucvu != null ?
                new ObjectParameter("chucvu", chucvu) :
                new ObjectParameter("chucvu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_themnv", hoParameter, tenlotParameter, tenParameter, ngaysinhParameter, sdtParameter, chucvuParameter);
        }
    
        public virtual int sp_themphong(string maphong, string loaiphong, string capdo, Nullable<decimal> giaphong, string tinhtrang)
        {
            var maphongParameter = maphong != null ?
                new ObjectParameter("maphong", maphong) :
                new ObjectParameter("maphong", typeof(string));
    
            var loaiphongParameter = loaiphong != null ?
                new ObjectParameter("loaiphong", loaiphong) :
                new ObjectParameter("loaiphong", typeof(string));
    
            var capdoParameter = capdo != null ?
                new ObjectParameter("capdo", capdo) :
                new ObjectParameter("capdo", typeof(string));
    
            var giaphongParameter = giaphong.HasValue ?
                new ObjectParameter("giaphong", giaphong) :
                new ObjectParameter("giaphong", typeof(decimal));
    
            var tinhtrangParameter = tinhtrang != null ?
                new ObjectParameter("tinhtrang", tinhtrang) :
                new ObjectParameter("tinhtrang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_themphong", maphongParameter, loaiphongParameter, capdoParameter, giaphongParameter, tinhtrangParameter);
        }
    
        public virtual ObjectResult<sp_thongtincn_Result> sp_thongtincn(Nullable<int> tentk)
        {
            var tentkParameter = tentk.HasValue ?
                new ObjectParameter("tentk", tentk) :
                new ObjectParameter("tentk", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_thongtincn_Result>("sp_thongtincn", tentkParameter);
        }
    
        public virtual int sp_traphong(string maphong, Nullable<int> maThue, Nullable<int> mancc)
        {
            var maphongParameter = maphong != null ?
                new ObjectParameter("maphong", maphong) :
                new ObjectParameter("maphong", typeof(string));
    
            var maThueParameter = maThue.HasValue ?
                new ObjectParameter("maThue", maThue) :
                new ObjectParameter("maThue", typeof(int));
    
            var manccParameter = mancc.HasValue ?
                new ObjectParameter("mancc", mancc) :
                new ObjectParameter("mancc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_traphong", maphongParameter, maThueParameter, manccParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int sp_xoakh(Nullable<int> makh)
        {
            var makhParameter = makh.HasValue ?
                new ObjectParameter("makh", makh) :
                new ObjectParameter("makh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_xoakh", makhParameter);
        }
    
        public virtual int sp_xoanv(Nullable<int> manv)
        {
            var manvParameter = manv.HasValue ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_xoanv", manvParameter);
        }
    
        public virtual int sp_xoaphong(string maphong)
        {
            var maphongParameter = maphong != null ?
                new ObjectParameter("maphong", maphong) :
                new ObjectParameter("maphong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_xoaphong", maphongParameter);
        }
    }
}
