//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thue
    {
        public int maThue { get; set; }
        public string maphong { get; set; }
        public int maKh { get; set; }
        public System.DateTime ngaythue { get; set; }
        public Nullable<System.DateTime> ngaytra { get; set; }
        public string tinhtrang { get; set; }
        public Nullable<decimal> tongiten { get; set; }
        public Nullable<int> nguoiCapnhat { get; set; }
    
        public virtual Khachhang Khachhang { get; set; }
        public virtual Nhanvien Nhanvien { get; set; }
        public virtual Phong Phong { get; set; }
    }
}
